# Generated by Django 3.1.3 on 2020-12-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_modeltest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTest',
        ),
    ]
